apiVersion: v2
name: snapshot-controller
version: 0.1.0
description: Thin wrapper for Snapshot Controller
dependencies:
  - name: snapshot-controller
    # renovate: datasource=helm registryUrl=https://piraeus.io/helm-charts/ depName=snapshot-controller
    version: "5.1.0"
    repository: "https://piraeus.io/helm-charts/"
