apiVersion: v2
name: descheduler
version: 0.1.2
description: Thin wrapper for Kubernetes Descheduler
dependencies:
  - name: descheduler
    # renovate: datasource=helm registryUrl=https://kubernetes-sigs.github.io/descheduler depName=descheduler
    version: "0.37.0"
    repository: "https://kubernetes-sigs.github.io/descheduler"
