apiVersion: v2
name: cloudnative-pg
version: 0.2.0
description: Thin wrapper for CloudNative-PG operator and barman-cloud plugin
dependencies:
  - name: cloudnative-pg
    # renovate: datasource=helm registryUrl=https://cloudnative-pg.io/charts depName=cloudnative-pg
    version: "0.28.2"
    repository: "https://cloudnative-pg.io/charts/"
  - name: plugin-barman-cloud
    # renovate: datasource=helm registryUrl=https://cloudnative-pg.io/charts depName=plugin-barman-cloud
    version: "0.6.0"
    repository: "https://cloudnative-pg.io/charts/"
    condition: plugin-barman-cloud.enabled
