cloudnative-pg:
  fullnameOverride: cloudnative-pg
  namespace: cnpg-system
  replicaCount: 2

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node-role.kubernetes.io/control-plane
      operator: Exists

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 5m
      memory: 64Mi

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: cloudnative-pg
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: cloudnative-pg

plugin-barman-cloud:
  enabled: true
