vertical-pod-autoscaler:
  admissionController:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        memory: 64Mi
    podDisruptionBudget:
      enabled: false

  recommender:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 5m
        memory: 64Mi
      limits:
        memory: 128Mi
    podDisruptionBudget:
      enabled: false

  updater:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 5m
        memory: 64Mi
      limits:
        memory: 128Mi
    podDisruptionBudget:
      enabled: false
