apiVersion: v2
name: external-secrets
version: 0.1.0
description: Thin wrapper for External Secrets Operator
dependencies:
  - name: external-secrets
    # renovate: datasource=helm registryUrl=https://charts.external-secrets.io depName=external-secrets
    version: "2.4.1"
    repository: "https://charts.external-secrets.io"
