apiVersion: v2
name: crossplane
version: 0.1.0
description: Thin wrapper for Crossplane
dependencies:
  - name: crossplane
    # renovate: datasource=github-releases depName=crossplane/crossplane
    version: "v2.3.4"
    repository: "https://charts.crossplane.io/stable"
