kyverno:
  features:
    forceFailurePolicyIgnore:
      enabled: true

  config:
    preserve: false
    webhooks:
      namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          - kube-system
          - karpenter

  admissionController:
    rbac:
      clusterRole:
        extraResources:
          - apiGroups:
              - gateway.networking.k8s.io
            resources:
              - httproutes
              - grpcroutes
              - tlsroutes
            verbs:
              - list
              - get
    replicas: 2
    nodeSelector:
      node-type: system
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    container:
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 5m
          memory: 128Mi

  backgroundController:
    replicas: 1
    nodeSelector:
      node-type: system
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 5m
        memory: 64Mi

  cleanupController:
    replicas: 1
    nodeSelector:
      node-type: system
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 32Mi

  reportsController:
    replicas: 1
    nodeSelector:
      node-type: system
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 5m
        memory: 64Mi

  crds:
    migration:
      nodeSelector:
        node-type: system
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      podResources:
        limits:
          memory: 256Mi
        requests:
          cpu: 5m
          memory: 64Mi

  webhooksCleanup:
    nodeSelector:
      node-type: system
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 32Mi
