apiVersion: v2
name: spire
version: 0.1.0
description: Thin wrapper for SPIRE
dependencies:
  - name: spire
    # renovate: datasource=helm registryUrl=https://spiffe.github.io/helm-charts-hardened depName=spire
    version: "0.29.0"
    repository: "https://spiffe.github.io/helm-charts-hardened/"
