apiVersion: v2
name: cilium
version: 0.1.0
description: Thin wrapper for Cilium CNI
dependencies:
  - name: cilium
    # renovate: datasource=helm registryUrl=https://helm.cilium.io depName=cilium
    version: "1.19.5"
    repository: "https://helm.cilium.io/"
