apiVersion: v2
name: argocd
version: 0.1.0
description: Thin wrapper for Argo CD
dependencies:
  - name: argo-cd
    # renovate: datasource=docker depName=ghcr.io/argoproj/argo-helm/argo-cd
    version: "9.5.19"
    repository: "oci://ghcr.io/argoproj/argo-helm"
